version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 1024mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_USERNAME=${REDIS_USERNAME}

  app:
    build: .
    ports:
      - "8000:8000"
    container_name: app
    restart: always
    volumes:
      - .:/app
    env_file:
      - ./.env
  
  redis_consumer:
    build:
      context: .
      dockerfile: redis_main.Dockerfile
    command: python3 -m app.services.redis_main
    container_name: redis_consumer
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - ./.env
  
  redis_consumer2:
    build:
      context: .
      dockerfile: redis_main.Dockerfile
    command: python3 -m app.services.redis_main
    container_name: redis_consumer2
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - ./.env

  redis_service_delayed_msgs:
    build:
      context: .
      dockerfile: delayed_msgs.Dockerfile
    container_name: redis_service_delayed_msgs
    restart: always
    command: python3 delayed_msgs.py
    depends_on:
      - redis
    env_file:
      - ./.env

volumes:
  db_data:
  redis_data:
