version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8888:8000"
    container_name: app
    env_file:
      - ./.env
    volumes:
      - .:/app
