name: Dev Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11']

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Black
        uses: weibullguy/python-lint-plus@master
        with:
          use-black: true
          use-yapf: false
          use-isort: false
          use-docformatter: false
          use-pycodestyle: false
          use-autopep8: false
          use-pydocstyle: false
          use-mypy: false
          use-pylint: false
          use-flake8: false
          use-mccabe: false
          use-radon: false
          use-rstcheck: false
          use-check-manifest: false
          use-pyroma: false
  
  # telegram:
  #   name: Send Telegram Notification
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Notify Telegram on-Prod-Success
  #       uses: appleboy/telegram-action@master
  #       with:
  #         to: ${{ secrets.TELEGRAM_TO }}
  #         token: ${{ secrets.TELEGRAM_TOKEN }}
  #         message: |
  #           Hello ${{ github.actor }},
  #           Repository: Ktechhub API
  #           Commit: ${{ github.sha }}
  #                   ${{ github.event.head_commit.message }}
  #           STATUS: Pipeline passed successfully!

  # failure:
  #   name: Send Telegram Notification
  #   runs-on: ubuntu-latest
  #   needs: [build, telegram]
  #   if: failure()
  #   steps:
  #   - name: Notify Telegram on-Prod-Failure
  #     uses: appleboy/telegram-action@master
  #     with:
  #       to: ${{ secrets.TELEGRAM_TO }}
  #       token: ${{ secrets.TELEGRAM_TOKEN }}
  #       message: |
  #         Hello ${{ github.actor }},
  #         Repository: Ktechhub API
  #         Commit: ${{ github.sha }}
  #                 ${{ github.event.head_commit.message }}
  #         STATUS: Pipeline FAILED!